kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: dockercondemo
spec:
  selector:
    app: dockercondemo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: default
  name: dockercondemo
  labels:
    app: dockercondemo
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: dockercondemo
  template:
    metadata:
      labels:
        app: dockercondemo
    spec:
      containers:
      - image: dtr.olly.dtcntr.net/prod/demo-app:51
        name: dockercondemo-container
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 3
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dockercondemo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: demo.apps.olly.dtcntr.net
    http:
      paths:
      - path: /
        backend:
          serviceName: dockercondemo
          servicePort: 80
