version: '3.2'
services:
  frontend:
    image: ollypom/whale-demoapp:2
    environment:
      REDIS_URL: backend
      LOGO_COLOUR: blue
    networks: 
      - demoapp
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 2

  backend:
    image: redis
    volumes:
      - redisdata:/data
    networks:
      - demoapp

volumes:
  redisdata:

networks:
  demoapp:
    driver: overlay